# ==================== CREATE WIREGUARD CONFIGURATION ====================

log_info "Creating WireGuard configuration with proper syntax..."

# Create initial wg0.conf with proper syntax
cat > /etc/wireguard/wg0.conf <<EOF
# WireGuard Configuration for wg0
# Generated by xWireGuard Enterprise Installer v$SCRIPT_VERSION
# Created: $(date)

[Interface]
PrivateKey = $private_key
Address = $ipv4_address_pvt
ListenPort = $wg_port
EOF

# Add IPv6 address if available - FIXED: Using different delimiter for sed
if [[ -n $ipv6_address_pvt ]]; then
    # Use '|' as delimiter instead of '/' to avoid issues with IPv6 addresses
    sed -i "s|^Address = .*|&, $ipv6_address_pvt|" /etc/wireguard/wg0.conf
    log_info "Added IPv6 address: $ipv6_address_pvt"
fi

echo "Setting up Wireguard configuration ....."

# Add Wireguard Network configuration
echo "Setting up Wireguard Network ....."
ipv4_address_pvt0=$(convert_ipv4_format "$ipv4_address_pvt")
# Define the path to the iptables.sh script
cat <<EOF | tee -a "$iptables_script" >/dev/null
#!/bin/bash
# Wait for the network interface to be up
while ! ip link show dev $interface up; do
    sleep 1
done
# Set iptables rules for WireGuard
iptables -t nat -I POSTROUTING --source $ipv4_address_pvt0 -o $interface -j SNAT --to $ipv4_address
iptables -t nat -D POSTROUTING -o $interface -j MASQUERADE
# Set ip6tables rules for WireGuard (IPv6)
#ip6tables -t nat -I POSTROUTING --source ::/0 -o $interface -j SNAT --to $ipv6_address
# Add custom route for WireGuard interface
ip route add default dev wg0
# Add custom route for incoming traffic from WireGuard
ufw route allow in on wg0 out on $interface
EOF

cat <<EOF | tee -a /etc/systemd/system/wireguard-iptables.service >/dev/null
[Unit]
Description=Setup iptables rules for WireGuard
After=network-online.target
[Service]
Type=oneshot
ExecStart=$iptables_script
[Install]
WantedBy=multi-user.target
EOF

chmod +x $iptables_script
# Uncomment the ip6tables command if IPv6 is available - FIXED: Check correct variable
if [[ -n $ipv6_address_pvt ]] && grep -q "#ip6tables" "$iptables_script"; then
    sed -i 's/#ip6tables/ip6tables/' "$iptables_script" >/dev/null
    # Escape the IPv6 address for sed
    escaped_ipv6=$(echo "$ipv6_address_pvt" | sed 's|/|\\/|g')
    sed -i "s|::/0|$escaped_ipv6|" "$iptables_script" >/dev/null
fi

systemctl enable wireguard-iptables.service --quiet

# ==================== ADD DNS PROTECTION RULES TO WIREGUARD CONFIG ====================

log_info "Adding DNS protection rules to WireGuard configuration..."

# Build DNS rules with proper syntax
cat >> /etc/wireguard/wg0.conf <<EOF

# ===== ENTERPRISE DNS PROTECTION RULES =====
# Applied by WireGuard Enterprise Installer v$SCRIPT_VERSION

# Pre-up: Ensure DNS is locked (FIXED: Proper spacing)
PreUp = chattr -i /etc/resolv.conf 2>/dev/null || true
PreUp = echo "nameserver 127.0.0.1" > /etc/resolv.conf
PreUp = chattr +i /etc/resolv.conf 2>/dev/null || true

# Post-up: Apply DNS traffic rules
EOF

# Add individual DNS accept rules with proper spacing
IFS=',' read -ra dns_array <<< "$dns"
for dns_server in "${dns_array[@]}"; do
    dns_server=$(echo "$dns_server" | xargs)
    if [[ $dns_server =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "PostUp = iptables -I OUTPUT -p udp --dport 53 -d $dns_server -j ACCEPT" >> /etc/wireguard/wg0.conf
        echo "PostUp = iptables -I OUTPUT -p tcp --dport 53 -d $dns_server -j ACCEPT" >> /etc/wireguard/wg0.conf
    fi
done

# Add the remaining rules
cat >> /etc/wireguard/wg0.conf <<EOF
PostUp = iptables -I OUTPUT -p udp --dport 53 -j DROP
PostUp = iptables -I OUTPUT -p tcp --dport 53 -j DROP
PostUp = sysctl -w net.ipv4.conf.all.rp_filter=1
PostUp = sysctl -w net.ipv4.conf.default.rp_filter=1

# Post-down: Clean up rules
PostDown = iptables -D OUTPUT -p udp --dport 53 -j DROP 2>/dev/null || true
PostDown = iptables -D OUTPUT -p tcp --dport 53 -j DROP 2>/dev/null || true
EOF

# Add DNS-specific cleanup rules
IFS=',' read -ra dns_array <<< "$dns"
for dns_server in "${dns_array[@]}"; do
    dns_server=$(echo "$dns_server" | xargs)
    if [[ $dns_server =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "PostDown = iptables -D OUTPUT -p udp --dport 53 -d $dns_server -j ACCEPT 2>/dev/null || true" >> /etc/wireguard/wg0.conf
        echo "PostDown = iptables -D OUTPUT -p tcp --dport 53 -d $dns_server -j ACCEPT 2>/dev/null || true" >> /etc/wireguard/wg0.conf
    fi
done

log_success "WireGuard configuration created with proper syntax"
